### ISSUE TITLE
`pytest-tornasync` appears to be a *run-time* dependency?

### ISSUE THREAD

**Issue by dhirschfeld** [voila-dashboards/voila#728] opened 2020-09-26 07:44 UTC
Adding `voila` as a dependency to a `conda` meta-package I'm building breaks our CI with the below error:
```
C:\agent\_work\1\s>exit /B 0 

Traceback (most recent call last):

  File "C:\Miniconda\envs\test-1512\lib\site-packages\_pytest\config\__init__.py", line 689, in import_plugin

    __import__(importspec)

ModuleNotFoundError: No module named 'pytest_tornasync'
```

Specifying `pytest_tornasync` as a direct dependency then fixes the CI.

**Comment by maartenbreddels** [comment] 2020-10-19 09:22
I'm wondering if this is jupyter_server:
https://github.com/jupyter/jupyter_server/blob/23b0a84ffb6599db97b37f66f80dba5c43f3a0c9/setup.py#L63

How can we reproduce this?

**Comment by adriendelsalle** [comment] 2020-11-09 11:22
Hi! 
I just faced the same issue.

Please find hereafter the reproducing steps @maartenbreddels 

Installing `jupyter_server` instead of `Voilà` gives the same outputs due to the entrypoint you mentioned.
This issue should be transfered to the `jupyter-server` project.

I'm not sure that an entrypoint can be conditionally generated for an extras_require entry.

I hope this help!

---

1. Use `pytest`

Using a `simple_test.py` file only containing a trivial assertion:

``` bash
cat simple_test.py
def test_assert_true():
    assert True
```

``` bash
conda create -n bug_pytest -c conda-forge pytest
conda activate bug_pytest 
pytest simple_test.py  # <-- runs fine
```

2. Then install `Voilà` (or `jupyter-server`)
``` bash
conda install -c conda-forge voila  # or jupyter_server
pytest simple_test.py  # <-- now throws an error
...
ImportError: Error importing plugin "pytest_tornasync": No module named 'pytest_tornasync'
```

3. Finally install `pytest_tornasync`

``` bash
pip install pytest_tornasync  # Not packaged with conda
pytest simple_test.py  # <-- ImportError fixed
```

**Comment by vidartf** [comment] 2021-01-06 12:25
I think this should be fixed in jupyter_server now ?

**Closed** 2021-01-06 13:30 UTC
