### ISSUE TITLE
ipywidget filelink does not work in voila

### ISSUE THREAD

**Issue by omontue** [voila-dashboards/voila#618] opened 2020-05-22 12:58 UTC
when using the ipywidget filelink with jupyter notebook it works well. After running the same with voila I get the message 403: Forbidden.

**Comment by SylvainCorlay** [comment] 2020-05-22 14:03
Hello, what do you mean by a file link?

Voilà purposely does not serve the files that are local to the notebook, which may contain source code, or data, that the dashboard author does not want to expose.

**Comment by omontue** [comment] 2020-05-22 18:37
Hello Sylvain,
I refer to https://ipython.readthedocs.io/en/stable/api/generated/IPython.display.html

I want to create a CSV file from a dataframe and allow the user to download it using the filelink.
It works with Jupyter Notebook but when using Voila I get the error.

Is there a workaround?

Thanks a lot,
Oliver

**Comment by vidartf** [comment] 2020-06-16 09:55
You can allow certain files by using the `file_whitelist` config option:

https://github.com/voila-dashboards/voila/blob/a3c80fcc11a9dbba298345f5947695a50998e87c/voila/configuration.py#L36-L44

**Comment by maartenbreddels** [comment] 2020-08-31 09:26
Duplicate of #560 see that issue for how to achieve this.

**Closed by maartenbreddels** 2020-08-31 09:26 UTC
