### ISSUE TITLE
Widgets not rendering with xeus-python kernel.

### ISSUE THREAD

**Issue by trungleduc** [voila-dashboards/voila#947] opened 2021-09-03 14:17 UTC
## Description

Widgets do not render in Voila with `xeus-python`  kernel.

## Reproduce

1. Create new environnement:
```bash
 mamba create -n testenv python=3.9 jupyterlab voila ipywidgets xeus-python -y
```
2. Create a new notebook  with content:
```python
from ipywidgets import widgets
widgets.Button(description="Click Me!")
```
2. Select `XPython` as kernel then save notebook.
3. Start `Voila` with the newly created notebook.
4. See error :
```python
Traceback (most recent call last):

  File "/home/********/miniconda3/lib/python3.9/site-packages/voila/handler.py", line 209, in _jinja_cell_generator
    output_cell = await task

  File "/home/********/miniconda3/lib/python3.9/site-packages/voila/execute.py", line 69, in execute_cell
    result = await self.async_execute_cell(cell, cell_index, store_history)

  File "/home/********/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 846, in async_execute_cell
    exec_reply = await self.task_poll_for_reply

  File "/home/********/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 632, in _async_poll_for_reply
    await asyncio.wait_for(task_poll_output_msg, self.iopub_timeout)

  File "/home/********/miniconda3/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()

  File "/home/********/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 665, in _async_poll_output_msg
    self.process_message(msg, cell, cell_index)

  File "/home/********/miniconda3/lib/python3.9/site-packages/nbclient/client.py", line 904, in process_message
    display_id = content.get('transient', {}).get('display_id', None)

AttributeError: 'NoneType' object has no attribute 'get'
```

## Expected behavior

A button with text "Click Me!" should be shown.

## Context

- Version:
```
ipykernel                 6.3.1            py39hef51801_0    conda-forge
ipython                   7.27.0           py39hef51801_0    conda-forge
ipywidgets                7.6.4              pyhd8ed1ab_0    conda-forge
jupyter_client            7.0.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
jupyter_server            1.10.2             pyhd8ed1ab_0    conda-forge
jupyterlab                3.1.10             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.7.2              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.0.1              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.4              pyhd8ed1ab_0    conda-forge
nbconvert                 6.1.0            py39hf3d152e_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
notebook                  6.4.3              pyha770c72_0    conda-forge
python                    3.9.7           h49503c6_0_cpython    conda-forge
tornado                   6.1              py39h3811e60_1    conda-forge
traitlets                 5.1.0              pyhd8ed1ab_0    conda-forge
voila                     0.2.11             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.1            py39hf3d152e_4    conda-forge
xeus                      1.0.4                h7d0c39e_0    conda-forge
xeus-python               0.12.5           py39h1aaad98_2    conda-forge
```
- Operating System and version: Windows 10
- Browser and version: Chrome  92.0.4515.159

**Comment by jtpio** [comment] 2021-09-06 08:32
Thanks @trungleduc for spotting this and the detailed report :+1: 

Looks like this might be an issue with the underlying `nbclient` library?

**Comment by jtpio** [comment] 2021-09-06 08:32
Thinking we could also add a test for this in https://github.com/voila-dashboards/voila/tree/master/tests

Or make sure they render with xeus-python as a visual regression test: https://github.com/voila-dashboards/voila/issues/948

**Comment by trungleduc** [comment] 2021-09-06 10:35
> Thanks @trungleduc for spotting this and the detailed report 👍
> 
> Looks like this might be an issue with the underlying `nbclient` library?

Yes, i think so.

**Comment by martinRenou** [comment] 2021-09-09 12:37
This will be fixed upstream https://github.com/jupyter-xeus/xeus-python/pull/480

**Closed by martinRenou** 2021-09-09 12:37 UTC
Labels: bug
